/*
 * generated by Xtext
 */
package br.com.maisha.wind.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TerraUiModule extends br.com.maisha.wind.ui.AbstractTerraUiModule {
	public TerraUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
