/*
 * generated by Xtext
 */
package br.com.maisha.wind.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

import br.com.maisha.wind.services.TerraGrammarAccess;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class TerraFormatter extends AbstractDeclarativeFormatter {
	
	@Override
	protected void configureFormatting(FormattingConfig c) {
		TerraGrammarAccess grammarAccess = (TerraGrammarAccess) getGrammarAccess();
		c.setAutoLinewrap(120);
		
		c.setLinewrap(2).after(grammarAccess.getPackageDeclarationRule());
		c.setLinewrap(2).around(grammarAccess.getImportRule());
		
		c.setLinewrap(2).around(grammarAccess.getDomainObjectRule());
		c.setLinewrap().around(grammarAccess.getObjectPropertyRule());
		c.setLinewrap(2).around(grammarAccess.getAttributeRule());
		c.setLinewrap().around(grammarAccess.getAttributePropertyRule());
		c.setLinewrap(2).around(grammarAccess.getOperationRule());
		c.setLinewrap().around(grammarAccess.getOperationPropertyRule());
		c.setLinewrap(2).around(grammarAccess.getValidationRule());
		c.setLinewrap().around(grammarAccess.getValidationRuleRule());

		c.setIndentationIncrement().before(grammarAccess.getObjectPropertyRule());
		c.setIndentationDecrement().after(grammarAccess.getObjectPropertyRule());
		
		
		c.setIndentationIncrement().before(grammarAccess.getAttributeRule());
		c.setIndentationDecrement().after(grammarAccess.getAttributeRule());
		
		c.setIndentationIncrement().before(grammarAccess.getAttributePropertyRule());
		c.setIndentationDecrement().after(grammarAccess.getAttributePropertyRule());
		
		c.setIndentationIncrement().before(grammarAccess.getOperationRule());
		c.setIndentationDecrement().after(grammarAccess.getOperationRule());
		
		c.setIndentationIncrement().before(grammarAccess.getOperationPropertyRule());
		c.setIndentationDecrement().after(grammarAccess.getOperationPropertyRule());
		
		c.setIndentationIncrement().before(grammarAccess.getValidationRuleRule());
		c.setIndentationDecrement().after(grammarAccess.getValidationRuleRule());
		c.setIndentationDecrement().after(grammarAccess.getValidationRule());
		
		c.setIndentationDecrement().after(grammarAccess.getDomainObjectRule());
		
		
		c.setLinewrap(0, 1, 2).before(grammarAccess.getSL_COMMENTRule());
		c.setLinewrap(0, 1, 2).before(grammarAccess.getML_COMMENTRule());
		c.setLinewrap(0, 1, 1).after(grammarAccess.getML_COMMENTRule());
	}
}
