/*
 * generated by Xtext
 */
package br.com.maisha.wind;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TerraRuntimeModule extends br.com.maisha.wind.AbstractTerraRuntimeModule {

}
