<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="terra"
    nsURI="http://www.com.br/maisha/wind/terra/Terra" nsPrefix="terra">
  <eClassifiers xsi:type="ecore:EClass" name="DomainObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="ecore:EClass platform:/resource/br.com.maisha.wind.terra/src-gen/br/com/maisha/wind/terra/Terra.ecore#//PackageDeclaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass platform:/resource/br.com.maisha.wind.terra/src-gen/br/com/maisha/wind/terra/Terra.ecore#//Import"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="ecore:EClass platform:/resource/br.com.maisha.wind.terra/src-gen/br/com/maisha/wind/terra/Terra.ecore#//ObjectProperty"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass platform:/resource/br.com.maisha.wind.terra/src-gen/br/com/maisha/wind/terra/Terra.ecore#//Attribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="ecore:EClass platform:/resource/br.com.maisha.wind.terra/src-gen/br/com/maisha/wind/terra/Terra.ecore#//Operation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validations" upperBound="-1"
        eType="ecore:EClass platform:/resource/br.com.maisha.wind.terra/src-gen/br/com/maisha/wind/terra/Terra.ecore#//Validation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EEnum platform:/resource/br.com.maisha.wind.terra/src-gen/br/com/maisha/wind/terra/Terra.ecore#//ObjectPropertyName"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="ecore:EClass platform:/resource/br.com.maisha.wind.terra/src-gen/br/com/maisha/wind/terra/Terra.ecore#//AttributeProperty"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EEnum platform:/resource/br.com.maisha.wind.terra/src-gen/br/com/maisha/wind/terra/Terra.ecore#//AttributePropertyName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validValues" eType="ecore:EClass platform:/resource/br.com.maisha.wind.terra/src-gen/br/com/maisha/wind/terra/Terra.ecore#//Array"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum platform:/resource/br.com.maisha.wind.terra/src-gen/br/com/maisha/wind/terra/Terra.ecore#//OperationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="ecore:EClass platform:/resource/br.com.maisha.wind.terra/src-gen/br/com/maisha/wind/terra/Terra.ecore#//OperationProperty"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EEnum platform:/resource/br.com.maisha.wind.terra/src-gen/br/com/maisha/wind/terra/Terra.ecore#//OperationPropertyName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validValues" eType="ecore:EClass platform:/resource/br.com.maisha.wind.terra/src-gen/br/com/maisha/wind/terra/Terra.ecore#//Array"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Validation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="ecore:EClass platform:/resource/br.com.maisha.wind.terra/src-gen/br/com/maisha/wind/terra/Terra.ecore#//ValidationRule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Array">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperationType">
    <eLiterals name="groovy" literal="groovy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PresentationType">
    <eLiterals name="text" literal="text"/>
    <eLiterals name="radio" value="1" literal="radio"/>
    <eLiterals name="checkbox" value="2" literal="checkbox"/>
    <eLiterals name="combo" value="3" literal="combo"/>
    <eLiterals name="list" value="4" literal="list"/>
    <eLiterals name="textarea" value="5" literal="textarea"/>
    <eLiterals name="date" value="6" literal="date"/>
    <eLiterals name="related" value="7" literal="related"/>
    <eLiterals name="embedded_object" value="8" literal="embedded_object"/>
    <eLiterals name="group" value="9" literal="group"/>
    <eLiterals name="folder" value="10" literal="folder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AttributePropertyName">
    <eLiterals name="x" literal="x"/>
    <eLiterals name="y" value="1" literal="y"/>
    <eLiterals name="colspan" value="2" literal="colspan"/>
    <eLiterals name="rowspan" value="3" literal="rowspan"/>
    <eLiterals name="disabled" value="4" literal="disabled"/>
    <eLiterals name="icon" value="5" literal="icon"/>
    <eLiterals name="width" value="6" literal="width"/>
    <eLiterals name="height" value="7" literal="height"/>
    <eLiterals name="tooltip" value="8" literal="tooltip"/>
    <eLiterals name="group" value="9" literal="group"/>
    <eLiterals name="visibleInEdition" value="10" literal="visibleInEdition"/>
    <eLiterals name="visibleInGrid" value="11" literal="visibleInGrid"/>
    <eLiterals name="content" value="12" literal="content"/>
    <eLiterals name="value" value="13" literal="value"/>
    <eLiterals name="validValues" value="14" literal="validValues"/>
    <eLiterals name="validation" value="15" literal="validation"/>
    <eLiterals name="required" value="16" literal="required"/>
    <eLiterals name="max_length" value="17" literal="max_length"/>
    <eLiterals name="min_length" value="18" literal="min_length"/>
    <eLiterals name="range" value="19" literal="range"/>
    <eLiterals name="mask" value="20" literal="mask"/>
    <eLiterals name="event" value="21" literal="event"/>
    <eLiterals name="toString" value="22" literal="toString"/>
    <eLiterals name="onetomany" value="23" literal="onetomany"/>
    <eLiterals name="manytoone" value="24" literal="manytoone"/>
    <eLiterals name="transient" value="25" literal="transient"/>
    <eLiterals name="folder" value="26" literal="folder"/>
    <eLiterals name="presentation_type" value="27" literal="presentation_type"/>
    <eLiterals name="sequence" value="28" literal="sequence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperationPropertyName">
    <eLiterals name="disabled" literal="disabled"/>
    <eLiterals name="icon" value="1" literal="icon"/>
    <eLiterals name="tooltip" value="2" literal="tooltip"/>
    <eLiterals name="visible" value="3" literal="visible"/>
    <eLiterals name="file" value="4" literal="file"/>
    <eLiterals name="validWhen" value="5" literal="validWhen"/>
    <eLiterals name="is_filter" value="6" literal="is_filter"/>
    <eLiterals name="validate" value="7" literal="validate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ObjectPropertyName">
    <eLiterals name="open_filtering" literal="open_filtering"/>
    <eLiterals name="event_handler" value="1" literal="event_handler"/>
  </eClassifiers>
</ecore:EPackage>
