/*
* generated by Xtext
*/
package br.com.maisha.wind.terra.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TerraAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("br/com/maisha/wind/terra/parser/antlr/internal/InternalTerra.tokens");
	}
}
