/*
 * generated by Xtext
 */
package br.com.maisha.wind.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class TerraDescriptionLabelProvider extends
		DefaultDescriptionLabelProvider {

}
