/*
* generated by Xtext
*/
package br.com.maisha.wind.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class TerraOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
