/*
* generated by Xtext
*/
package br.com.maisha.wind.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import br.com.maisha.wind.services.TerraGrammarAccess;

public class TerraParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TerraGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected br.com.maisha.wind.parser.antlr.internal.InternalTerraParser createParser(XtextTokenStream stream) {
		return new br.com.maisha.wind.parser.antlr.internal.InternalTerraParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DomainObject";
	}
	
	public TerraGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TerraGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
