/*
 * generated by Xtext
 */
package br.com.maisha.wind.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

import br.com.maisha.wind.terra.AttributeProperty;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class TerraDescriptionLabelProvider extends
		DefaultDescriptionLabelProvider {

	// Labels and icons can be computed like this:

	public Object text(AttributeProperty ap) {
		return ap.getName() + " DOOOX";
	}

}
