/*
 * generated by Xtext
 */
package br.com.maisha.wind.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import br.com.maisha.wind.terra.Attribute;
import br.com.maisha.wind.terra.AttributeProperty;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class TerraLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public TerraLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}


}
