/*
* generated by Xtext
*/
package br.com.maisha.wind.ui.contentassist;

import br.com.maisha.wind.ui.contentassist.AbstractTerraProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TerraProposalProvider extends AbstractTerraProposalProvider {

}
