/*
 * generated by Xtext
 */
package br.com.maisha.wind.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TerraExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return br.com.maisha.wind.ui.internal.TerraActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return br.com.maisha.wind.ui.internal.TerraActivator.getInstance().getInjector("br.com.maisha.wind.Terra");
	}
	
}
